name: Update Space Shooter GIF
on:
  schedule:
    # cron syntax requires quotes
    cron: "0 0 * * *" 
  workflow_dispatch:

permissions:
  # Permissions must be defined with correct indentation
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: cz19707/gh-space-shooter@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-path: assets/space-shooter.gif
          strategy: random

